# Generated by Django 4.1.9 on 2023-06-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=10)),
                ("available_seats", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=10)),
                ("last_name", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="university_app.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=10)),
                ("last_name", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="university_app.course"
                    ),
                ),
            ],
        ),
    ]
