# Generated by Django 4.1.9 on 2023-06-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="university_app.course"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="university_app.course"),
        ),
    ]
