# Generated by Django 4.1.9 on 2023-06-14 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university_app", "0002_alter_student_course_alter_teacher_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="available_seats",
        ),
    ]
