# Generated by Django 4.1.9 on 2023-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university_app", "0003_remove_course_available_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="available_seats",
            field=models.IntegerField(default=150),
        ),
    ]
