# Generated by Django 4.1.9 on 2023-06-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university_app", "0004_course_available_seats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=20)),
            ],
        ),
    ]
