# Generated by Django 4.1.9 on 2023-06-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university_app", "0006_course_created_course_modified_student_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="<django.db.models.fields.CharField>", unique=True),
        ),
    ]
