# Generated by Django 4.1.9 on 2023-06-19 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university_app", "0009_course_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="slug",
        ),
    ]
