# Generated by Django 4.1.9 on 2023-06-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university_app", "0012_alter_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
